# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EatThis' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EatThis

  target 'EatThisTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EatThisUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
